<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AlatTesController extends Controller
{
    /**
     * Data dummy hardcode — akan diganti query ke tabel `alat_tes`
     * setelah backend modul Tes dibangun.
     */
    public const DUMMY_ALAT_TES = [
        [
            'id' => 1,
            'nama' => 'DISC',
            'format_dasar' => 'Skala Likert',
            'durasi_total_menit' => 30,
            'batas_waktu_per_soal_aktif' => false,
            'batas_waktu_per_soal_detik' => null,
            'is_sensitif' => false,
            'jumlah_soal' => 120,
            'dimensi' => [
                [
                    'nama_dimensi' => 'Dominance',
                    'kode' => 'D',
                    'bidang_psikogram' => 'Potensi Kerja',
                    'deskripsi_aspek' => 'Mengukur tingkat kepemimpinan dan kemauan mengontrol situasi.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Influence',
                    'kode' => 'I',
                    'bidang_psikogram' => 'Kepribadian',
                    'deskripsi_aspek' => 'Menilai kecenderungan berinteraksi sosial dan pengaruh terhadap orang lain.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Steadiness',
                    'kode' => 'S',
                    'bidang_psikogram' => 'Sikap Kerja',
                    'deskripsi_aspek' => 'Mengukur konsistensi, kestabilan sikap, dan daya tahan dalam pekerjaan.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Conscientiousness',
                    'kode' => 'C',
                    'bidang_psikogram' => 'Sikap Kerja',
                    'deskripsi_aspek' => 'Menilai tingkat ketelitian, patuhan pada prosedur, dan akuntabilitas.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
            ],
        ],
        [
            'id' => 2,
            'nama' => 'IST (Intelligence Structure Test)',
            'format_dasar' => 'Pilihan Ganda',
            'durasi_total_menit' => 90,
            'batas_waktu_per_soal_aktif' => true,
            'batas_waktu_per_soal_detik' => 60,
            'is_sensitif' => false,
            'jumlah_soal' => 200,
            'dimensi' => [
                [
                    'nama_dimensi' => 'Spatial Intelligence',
                    'kode' => 'SE',
                    'bidang_psikogram' => 'Intelektual',
                    'deskripsi_aspek' => 'Mengukur kemampuan memvisualisasikan dan memanipulasi objek secara spasial.',
                    'skor_min' => 80,
                    'skor_max' => 130,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 85,
                    'ambang_k' => 90,
                    'ambang_c' => 105,
                    'ambang_b' => 115,
                ],
                [
                    'nama_dimensi' => 'Verbal Intelligence',
                    'kode' => 'WA',
                    'bidang_psikogram' => 'Intelektual',
                    'deskripsi_aspek' => 'Menilai pemahaman konsep linguistik dan kemampuan ekspresi verbal.',
                    'skor_min' => 80,
                    'skor_max' => 130,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 85,
                    'ambang_k' => 90,
                    'ambang_c' => 105,
                    'ambang_b' => 115,
                ],
                [
                    'nama_dimensi' => 'Analytic Intelligence',
                    'kode' => 'AN',
                    'bidang_psikogram' => 'Intelektual',
                    'deskripsi_aspek' => 'Mengukur kemampuan berpikir analitis dan pemecahan masalah logis.',
                    'skor_min' => 80,
                    'skor_max' => 130,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 85,
                    'ambang_k' => 90,
                    'ambang_c' => 105,
                    'ambang_b' => 115,
                ],
                [
                    'nama_dimensi' => 'General Intelligence',
                    'kode' => 'GE',
                    'bidang_psikogram' => 'Intelektual',
                    'deskripsi_aspek' => 'Menilai kemampuan komprehensif dan integrasi berbagai aspek inteligensi.',
                    'skor_min' => 80,
                    'skor_max' => 130,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 85,
                    'ambang_k' => 90,
                    'ambang_c' => 105,
                    'ambang_b' => 115,
                ],
            ],
        ],
        [
            'id' => 3,
            'nama' => 'EPPS (Edwards Personal Preference Schedule)',
            'format_dasar' => 'Forced Choice',
            'durasi_total_menit' => 45,
            'batas_waktu_per_soal_aktif' => false,
            'batas_waktu_per_soal_detik' => null,
            'is_sensitif' => false,
            'jumlah_soal' => 225,
            'dimensi' => [
                [
                    'nama_dimensi' => 'Achievement',
                    'kode' => 'Ach',
                    'bidang_psikogram' => 'Potensi Kerja',
                    'deskripsi_aspek' => 'Mengukur kecenderungan mengejar prestasi standar tinggi dan ketekunan.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Dominance',
                    'kode' => 'Dom',
                    'bidang_psikogram' => 'Potensi Kerja',
                    'deskripsi_aspek' => 'Menilai keinginan mengarahkan orang lain dan mengambil keputusan.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Affiliation',
                    'kode' => 'Aff',
                    'bidang_psikogram' => 'Kepribadian',
                    'deskripsi_aspek' => 'Mengukur kebutuhan akan hubungan sosial dan acceptance dari orang lain.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
                [
                    'nama_dimensi' => 'Exhibition',
                    'kode' => 'Exp',
                    'bidang_psikogram' => 'Kepribadian',
                    'deskripsi_aspek' => 'Menilai keinginan tampil di depan orang dan menjadi perhatian publik.',
                    'skor_min' => 1,
                    'skor_max' => 10,
                    'tipe_kategori' => 'psikogram',
                    'ambang_r' => 2,
                    'ambang_k' => 4,
                    'ambang_c' => 6,
                    'ambang_b' => 8,
                ],
            ],
        ],
        [
            'id' => 4,
            'nama' => 'MMPI-2',
            'format_dasar' => 'Skala Likert',
            'durasi_total_menit' => 120,
            'batas_waktu_per_soal_aktif' => false,
            'batas_waktu_per_soal_detik' => null,
            'is_sensitif' => true,
            'jumlah_soal' => 567,
            'dimensi' => [
                [
                    'nama_dimensi' => 'Hypochondriasis (Hs)',
                    'kode' => 'Hs',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Mengukur kecemasan berlebihan tentang kesehatan dan gejala fisik.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Depression (D)',
                    'kode' => 'D',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Menilai tingkat depresi, perasaan tidak berdaya, dan kehilangan motivasi.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Hysteria (Hy)',
                    'kode' => 'Hy',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Mengukur kecenderungan menampilkan gejala fisik tanpa penyebab organik jelas.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Psychopathic Deviate (Pd)',
                    'kode' => 'Pd',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Menilai ketidaksesuaian sosial, penolakan norma, dan perilaku impulsif.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Masculinity-Femininity (Mf)',
                    'kode' => 'Mf',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Mengukur minat tradisional laki-laki/perempuan dan peran gender.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Paranoia (Pa)',
                    'kode' => 'Pa',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Menilai rasa curiga, pengkhianatan yang dirasakannya, dan sensitivitas.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Psychasthenia (Pt)',
                    'kode' => 'Pt',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Mengukur obsesi, kompulsivitas, ansietas kronis, dan keraguan diri.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Schizophrenia (Sc)',
                    'kode' => 'Sc',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Menilaian gejala disfungsional, bizarritas kognitif, dan isolasi sosial.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Hypomania (Ma)',
                    'kode' => 'Ma',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Mengukur tingkat euforia, agitasi manik, dan energi eksternal berlebih.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
                [
                    'nama_dimensi' => 'Social Introversion (Si)',
                    'kode' => 'Si',
                    'bidang_psikogram' => 'Sensitif',
                    'deskripsi_aspek' => 'Menilai kecenderungan menarik diri dari interaksi sosial dan introvert.',
                    'skor_min' => 40,
                    'skor_max' => 90,
                    'tipe_kategori' => 'klinis',
                    'ambang_normal' => 64,
                    'ambang_perlu_perhatian' => 74,
                ],
            ],
        ],
    ];

    public function index(): View
    {
        return view('admin.alat-tes.index', [
            'alatTes' => self::DUMMY_ALAT_TES,
        ]);
    }

    public function tambah(): View
    {
        return view('admin.alat-tes.tambah', [
            'pilihanFormat' => ['Pilihan Ganda', 'Skala Likert', 'Forced Choice'],
        ]);
    }

    public function simpan(Request $request)
    {
        return redirect()
            ->route('admin.alat-tes.index')
            ->with('sukses', 'Fitur simpan akan aktif setelah backend selesai dibangun.');
    }
}